// The back matter's content, kept apart from its DOM the same way menu_state
// is kept apart from menu. Everything here is a checkable claim, and the tests
// in tests/about.test.js hold the two that rot on their own — the Three.js
// version and the narration model — against the files that actually set them.
//
// Sources: the translation and lineage facts come from the header of
// book/gateless-gate.md; THREE_VERSION from lib/THREE_VERSION.txt; TTS_MODEL
// from scripts/lib/narration-voice.js.

export const SITE = 'https://frankforce.com';
export const SOURCE_URL = 'https://sacred-texts.com/bud/glg/index.htm';
// Where the book is built. Named for the repository the published site is
// served from (killedbyapixel.github.io/GatelessGate/), which is the canonical
// spelling — the underscored form some remotes carry is an old name GitHub
// still redirects.
export const REPO_URL = 'https://github.com/KilledByAPixel/GatelessGate';
// The licence the book ships under. The repository carries the full legal text
// in LICENSE and scopes it in NOTICE.md — what is the author's to license and
// what is not (the 1934 translation is public domain; Three.js is MIT). This
// page links the human-readable deed, which is what a reader wants.
export const LICENSE_URL = 'https://creativecommons.org/licenses/by-nc-nd/4.0/';
// The whole book as one Markdown page, generated by scripts/build-book.js and
// served from the site root beside index.html. Relative, so it works the same
// on the site, on a local http-server, and in the repo.
export const BOOK_MD = 'THE-GATELESS-GATE.md';

// Three.js ships as 0.MINOR.PATCH and is spoken of as rMINOR: 0.185.1 is r185.
export const THREE_VERSION = 'r185';
// What the narration was ACTUALLY baked with, per audio/narration/manifest.json.
// Not what scripts/lib/narration-voice.js defaults to: the bake takes --provider
// and --preset flags, so the script's constants are only its defaults and the
// manifest is the sole record of what shipped. The two drifted the day the whole
// reading was re-baked in Gemini and this page went on crediting OpenAI.
export const TTS_MODEL = 'gemini-3.1-flash-tts-preview';

// The repository, called out on its own line under the About head rather than
// left buried mid-paragraph (Frank: "put the github link a bit more
// prominently since it is kind of important for this version") — an
// open-source book should say so where the reader's eye lands first, not
// four sections down. Rendered by about.js right below the heading; the
// in-paragraph mention in 'This edition' stays, the way print repeats what
// matters.
export const REPO_CALLOUT = {
  lead: 'Free and open source: ',
  text: 'github.com/KilledByAPixel/GatelessGate',
  href: REPO_URL,
};

// A part is either a string or a [text, href] pair for the few places a link
// earns its keep.
export const SECTIONS = [
  {
    label: 'The translation',
    parts: [
      "The English text is Nyogen Senzaki and Paul Reps's rendering of the "
      + 'Mumonkan, privately printed by John Murray in Los Angeles in 1934. That '
      + 'printing is in the United States public domain; its copyright was never '
      + 'renewed. Reps later expanded this material into Zen Flesh, Zen Bones '
      + '(1957), the version most readers know. Archaic verb forms and pronouns, '
      + 'which survive here and there in the capping verses, have been lightly '
      + "modernised; Mumon's commentaries were already in plain modern English. "
      + "Other small editorial changes have been made: bracketed translator's "
      + 'notes let go where they explained a koan before it had finished asking, '
      + 'and the like. Transcribed from ',
      ['sacred-texts.com', SOURCE_URL],
      '.',
    ],
  },
  {
    // The 1934 translation carries the cases and nothing else, so every word of
    // the preface and the back matter is new and has to say so — the more plainly
    // because it now also ships as a plain Markdown file that travels without
    // this page attached to it.
    label: 'The front and back matter',
    parts: [
      "Mumon's preface, his afterword, the Zen Warnings and Amban's letter are not "
      + 'part of the 1934 translation, which carries only the cases. They were '
      + 'translated for this edition from the Chinese of the Taisho canon (CBETA '
      + 'T48n2005), in three independent passes made blind to one another and to any '
      + 'existing English version (a philological one, one in Song Chan idiom, and '
      + 'one in plain English). The three were then compared and every divergence of '
      + 'meaning taken back to the Chinese and settled by hand. It is a new rendering '
      + 'and worth reading as one: it has had no scholarly review, and the Chinese '
      + 'text it works from was not independently collated against a second witness.',
    ],
  },
  {
    label: 'The book',
    parts: [
      'The Gateless Gate was compiled in 1228 by the Chinese master Ekai, called '
      + 'Mumon (Wumen Huikai). It gathers forty-eight koans, each followed by his '
      + 'own commentary and a capping verse. The forty-ninth case is not his: '
      + 'Amban, described in the text only as a layman Zen student, added it '
      + 'afterwards as a bargain, complaining that Mumon was "like an old '
      + 'doughnut seller." It has travelled with the book ever since. The names '
      + 'throughout are the Japanese readings of Chinese ones, as Senzaki and Reps '
      + 'gave them: Joshu is Zhaozhou, Hyakujo is Baizhang.',
    ],
  },
  {
    label: 'This edition',
    parts: [
      'An interactive edition: every case staged as a small ink-painting '
      + 'diorama you can look around and touch, with narration, procedural '
      + 'ambience, and a timer for sitting. It is a book rather than a game: '
      + 'nothing here is a puzzle to solve, and nothing is locked. Made by Frank '
      + 'Force, ',
      ['frankforce.com', SITE],
      '. The code is ',
      ['on GitHub', REPO_URL],
      ', and the whole text also exists as ',
      ['a single plain page', BOOK_MD],
      ', generated from the same source this edition reads, for anyone who would '
      + 'rather read it straight through or keep a copy.',
    ],
  },
  {
    label: 'Rights',
    parts: [
      'This is a new edition of the Mumonkan, (c) 2026 Frank Force: the cases '
      + 'edited and modernised throughout, and a preface and back matter newly '
      + 'translated for it from the Chinese, which the 1934 text it rests on does '
      + 'not carry. The 1934 translation underneath that editing is in the public '
      + 'domain and stays that way. Everything else (the code, the dioramas, '
      + 'the audio, the narration, the new translations and the editing) is '
      + 'shared under ',
      ['Creative Commons BY-NC-ND 4.0', LICENSE_URL],
      ": credit it, don't sell it, don't publish a changed version of it. For "
      + "anything the licence doesn't cover, ask. Three.js, vendored here, is "
      + 'MIT-licensed and travels under its own terms.',
    ],
  },
  {
    label: 'Built with',
    parts: [
      `Three.js (${THREE_VERSION}) for the rendering, vendored rather than fetched. `
      + 'Every sound in the book except the narration is generated at runtime with '
      + 'the Web Audio API: the wind, the bells, the knocks and the drift are '
      + 'synthesised, not sampled. The narration was baked ahead of time with '
      + `Google's ${TTS_MODEL}. There is no build step, no framework, no `
      + 'analytics, and nothing at all is loaded from a third party while you '
      + 'read.',
    ],
  },
];
