// GENERATED by scripts/build-text.js from local/mumonkan-front-and-back-matter.md — do not edit by hand.
export default {
  "preface": {
    "slug": "preface",
    "title": "Mumon's Preface",
    "sections": [
      "preface"
    ],
    "labels": {
      "preface": ""
    },
    "text": {
      "preface": "The Buddha's teaching takes mind as its source, and no gate as the gate of the teaching.\nIf it is no gate, then how do you get through?\n\nHaven't you heard it said: what comes in by the gate is not the treasure of your own house;\nwhat you get from conditions has a start and a finish — it comes together and it falls\napart. Talk like that is raising waves where there is no wind, cutting a sore into healthy\nflesh. Worse still to snag on words and phrases and go hunting for a meaning. Swinging a\nstick at the moon. Scratching an itch through your boot. What has any of it to do with\nanything?\n\nIn the summer of the wuzi year of Shaoding I was head monk at Longxiang in Wenzhou. Monks\nkept coming to ask for instruction, so I took the old teachers' koans and used them as\ntile-shards for knocking at the gate, leading each student on according to what he needed.\nI copied them down as they came, and before I noticed there was a book. I never put them in\nany order. Forty-eight of them altogether. The whole thing goes under the name The Gateless\nGate.\n\nIf a man will go straight in with one blade and not care whether he lives, then eight-armed\nNezha cannot stop him, and even the twenty-eight patriarchs of India and the six of this\nland can only catch sight of him coming and beg for their lives. But hang back, and it is\nlike watching a rider go past outside the window. Blink, and he is long gone.\n\nThe verse:\n\n　　The great road has no gate.\n　　There are a thousand roads.\n　　Get through this barrier\n　　and you go alone through heaven and earth."
    }
  },
  "afterword": {
    "slug": "afterword",
    "title": "Afterword",
    "sections": [
      "afterword",
      "warnings",
      "amban"
    ],
    "labels": {
      "afterword": "Mumon's Afterword",
      "warnings": "Zen Warnings",
      "amban": "Amban's Letter"
    },
    "text": {
      "afterword": "The buddhas and the patriarchs, handing these encounters down, took the confession and closed\nthe case. Never a word to spare. They lift the lid off your skull and let your eyes out into\nthe daylight. What they want is for you to take hold of it here and now and not go looking for\nit from anybody else.\n\nAn all-round man of the first rank hears one of them raised and knows at once where it lands.\nThere is no doorway to go in by and no stairs to climb. He walks through the checkpoint\nswinging his arms and never asks the man on the gate.\n\nHave you not heard what Xuansha said? No gate is the gate of release. No intent is the intent\nof the man of the Way. And Baiyun said: You know perfectly well it is just this. So why can't\nyou get through?\n\nTalk like that is smearing milk on red clay. Get through the Gateless Gate and you have\nalready made a fool of Mumon. Fail to get through it and you have let yourself down. As the\nlines have it:\n\n　　The mind of nirvana is easy enough to make out.\n　　The wisdom that tells one thing from another is hard.\n　　Get that wisdom clear\n　　and house and country come to rest of themselves.\n\nFive days before the end of the summer retreat, the year the era changed to Shaoding.\nRespectfully set down by the monk Ekai, called Mumon, eighth in descent from Yangqi.",
      "warnings": "Follow the rules and hold the line:\n　　you tie yourself up without a rope.\n\n　　Range where you like with nothing in the way:\n　　the outsiders' road, the devil's army.\n\n　　Keep the mind clear and still:\n　　the crooked Zen of silent illumination.\n\n　　Do as you please and drop every tie:\n　　down you go into the deep pit.\n\n　　Wide awake, never dull:\n　　a chain on your leg and a board round your neck.\n\n　　Think good, think evil:\n　　hell and heaven.\n\n　　Opinions about Buddha, opinions about the teaching:\n　　iron mountains on both sides of you.\n\n　　Catch each thought the moment it stirs:\n　　a man fooling about with ghosts.\n\n　　Sit like a stump working at your concentration:\n　　making a living in a house of ghosts.\n\n　　Push on and you lose the sense of it;\n　　pull back and you break with the root.\n\n　　Neither on nor back:\n　　a corpse that is still breathing.\n\n　　Now say: how do you actually walk it?\n\n　　Put your back into it. Settle it in this life.\n　　Don't leave the rest of it to grind on you through endless ages.",
      "amban": "Old Zen master Mumon made his remarks on forty-eight koans, passing verdict on the koans of\nthe old worthies. It was very like a man selling fried cakes, who gets the customer to open his\nmouth and take one, and then the customer can neither swallow it nor spit it out.\n\nEven so. Amban would like to use the man's own stove while it is still hot, fry up one more,\nand round\nthe count out to the number of the Great Expansion, then send it back to him as before. And I\nwonder where the old master will get his teeth in. If he takes it in one bite, light will pour\nout and the ground will shake. If not, then even the forty-eight already there all turn to hot\nsand.\n\nSay it quick. Say it quick."
    }
  }
};
