// The kit facade: one import surface for koan modules (ctx.kit).
export { makeIsland } from './island.js';
export { makeGround, groundHeight } from './ground.js';
export { makeMountains } from './mountains.js';
export { makeForest } from './forest.js';
export { makeRocks, makeBushes, makeGrass, scatterPoints } from './scatter.js';
export { makeLantern } from './lantern.js';
export { makePath } from './path.js';
export { composeWorld } from './scenery.js';
export { makeMonk, aimMonk } from './monk.js';
export { makeTree } from './tree.js';
export { makePine, pineGeometry } from './pine.js';
export { makeGate } from './gate.js';
export { makeFlag } from './flag.js';
export { makeBlobShadow } from '../render/blobshadow.js';
export { makeLights, toonMaterial } from '../render/toon.js';
export { addOutlines } from '../render/outlines.js';
export { makeDog } from './dog.js';
export { makeTail } from './tail.js';
export { makeBuffalo } from './buffalo.js';
export { makeBuddha } from './buddha.js';
export { makeFlower } from './flower.js';
export { makeBowl } from './bowl.js';
export { makeWater } from './water.js';
export { makeHut } from './hut.js';
export { makeLattice } from './lattice.js';
export { makeAssembly } from './assembly.js';
