// The whole book as one Markdown file — the same text the interactive edition
// reads, rendered for people who want to read it plainly, search it, diff it, or
// keep a copy.
//
// Pure: it takes data and returns a string, so tests can hold the assembly to
// account without touching the filesystem. scripts/build-book.js is the half
// that reads and writes.
//
// One rule governs everything here: this file INVENTS NO TEXT. Every word of the
// book comes from src/koans/text/, and every word of the colophon comes from
// src/ui/about_state.js — the same source the About page renders. A second copy
// of the provenance prose is a second thing to keep true, and it would be wrong
// within a month.

import { LABELS } from '../../src/ui/scroll_state.js';

// Markdown collapses a single newline, and several sections of this book are
// verse whose line breaks are load-bearing — the Zen Warnings are thirteen
// stanzas of couplets. Two trailing spaces is CommonMark's hard break and is
// what GitHub renders; blank lines stay paragraph (and stanza) breaks.
export function preserveLines(text) {
  return String(text)
    .split('\n\n')
    .map((stanza) => stanza.split('\n').join('  \n'))
    .join('\n\n');
}

// An About-page part list — strings, with [text, href] pairs where a link earns
// its keep — rendered as Markdown.
export function partsToMarkdown(parts) {
  return parts.map((p) => (Array.isArray(p) ? `[${p[0]}](${p[1]})` : p)).join('');
}

// One page: a numbered case, or a matter page with no number.
function page({ entry, cases, matter }) {
  const out = [];
  if (entry.id === null) {
    const m = matter[entry.slug];
    out.push(`## ${m.title}`);
    for (const key of m.sections) {
      const label = m.labels[key];
      if (label) out.push(`**${label}**`);
      out.push(preserveLines(m.text[key]));
    }
    return out;
  }
  const c = cases[entry.id];
  out.push(`## ${entry.id}. ${c.title}`);
  // The three parts of a case, named the way the reading names them — LABELS is
  // the same table the scroll renders from, so the two cannot drift apart.
  for (const key of ['case', 'comment', 'verse']) {
    if (!c[key] || !c[key].trim()) continue;
    out.push(`**${LABELS[key]}**`);
    out.push(preserveLines(c[key]));
  }
  return out;
}

/**
 * @param entries  reading order, from spine.readingEntries — [{ id, slug, title }]
 * @param cases    src/koans/text/mumonkan.js default export, keyed by id
 * @param matter   src/koans/text/matter.js default export, keyed by slug
 * @param about    src/ui/about_state.js SECTIONS — [{ label, parts }]
 * @param script   the command that regenerates this file
 */
export function bookMarkdown({ entries, cases, matter, about, script }) {
  // The forty-eighth/forty-ninth distinction is the book's own joke and worth
  // keeping straight: Mumon collected forty-eight, and Amban added one more to
  // complain about the other forty-eight.
  const out = [
    '# The Gateless Gate',
    '*The Mumonkan: forty-eight koans collected by Mumon in 1228, Amban\'s forty-ninth, '
    + 'and Mumon\'s own preface and afterword.*',
    `<!-- GENERATED by ${script} — do not edit by hand. -->`,
    // A reader who lands here should learn what this edition is before reading a
    // word of it, not from a colophon at the far end. The full statement is in
    // "About this text" below; this is the sentence that cannot wait.
    'A new edition, © 2026 Frank Force, shared under '
    + '[CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/). '
    + 'The cases are edited and modernised throughout; the preface and back matter were '
    + 'translated for this edition from the Chinese and appear in no earlier English one. '
    + 'The 1934 translation underneath the editing is public domain and stays that way — '
    + 'see [NOTICE.md](NOTICE.md).',
    '---',
  ];

  for (const entry of entries) out.push(...page({ entry, cases, matter }));

  out.push('---', '## About this text');
  out.push(
    'This file is generated from the same text the interactive edition reads, so the '
    + 'two cannot disagree. To regenerate it after a text change, run '
    + `\`${script}\`.`,
  );
  for (const { label, parts } of about) {
    out.push(`**${label}**`);
    out.push(partsToMarkdown(parts));
  }

  // One trailing newline, and no blank line doubled anywhere: every element above
  // is a block, and joining on a blank line is what makes them blocks.
  return `${out.join('\n\n')}\n`;
}
