// Rerunnable: local/gateless-gate.txt -> src/koans/text/mumonkan.js
// Run: node scripts/build-text.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseMumonkan } from './lib/parse-mumonkan.js';
import { parseMatter } from './lib/parse-matter.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcTxt = path.join(root, 'local', 'gateless-gate.txt');
const outFile = path.join(root, 'src', 'koans', 'text', 'mumonkan.js');
const srcMatter = path.join(root, 'local', 'mumonkan-front-and-back-matter.md');
const outMatter = path.join(root, 'src', 'koans', 'text', 'matter.js');

// The two pages, and which translated piece fills each section. Keyed by the
// Chinese titles the parser returns, so re-titling a piece in English cannot
// silently empty a section.
const MATTER_PAGES = {
  preface: {
    slug: 'preface',
    title: "Mumon's Preface",
    // one section, deliberately unlabelled — the page title says it already
    parts: [['preface', '', '無門關自序']],
  },
  afterword: {
    slug: 'afterword',
    title: 'Afterword',
    parts: [
      ['afterword', "Mumon's Afterword", '後序'],
      ['warnings', 'Zen Warnings', '禪箴'],
      ['amban', "Amban's Letter", '安晚居士書'],
    ],
  },
};

// Hand-fixes for any case the uniform rules misparse (id -> partial entry). Empty for now.
const OVERRIDES = {};

const raw = fs.readFileSync(srcTxt, 'utf8');
const { about, cases } = parseMumonkan(raw);
for (const [id, patch] of Object.entries(OVERRIDES)) cases[id] = { ...cases[id], ...patch };

const ids = Object.keys(cases).map(Number).sort((a, b) => a - b);
const problems = [];
for (const id of ids) {
  for (const f of ['title', 'case', 'comment', 'verse']) {
    if (!cases[id][f] || !cases[id][f].trim()) problems.push(`case ${id}: empty ${f}`);
  }
}

console.log('id  verse-len  case-len  comment-len  title');
for (const id of ids) {
  const c = cases[id];
  console.log(
    String(id).padStart(2), String(c.verse.length).padStart(9), String(c.case.length).padStart(8),
    String(c.comment.length).padStart(11), ' ', c.title,
  );
}

if (ids.length !== 49) problems.push(`expected 49 entries, got ${ids.length}`);
if (problems.length) {
  console.error('\nBUILD FAILED:\n' + problems.join('\n'));
  process.exit(1);
}

const body = ids.map((id) => `  ${id}: ${JSON.stringify(cases[id])},`).join('\n');
const out = `// GENERATED by scripts/build-text.js from local/gateless-gate.txt — do not edit by hand.
export const about = ${JSON.stringify(about)};
export default {
${body}
};
`;
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, out);
console.log(`\nWrote ${outFile} (${ids.length} cases).`);

// ---- the front and back matter ----
// Its own module, never folded into mumonkan.js: build-narration.js re-bakes any
// unit whose text hash changed, and these pages have no narration. Keeping them
// apart makes it impossible for a preface edit to cost 147 files of TTS.
if (!fs.existsSync(srcMatter)) {
  console.error(`\nBUILD FAILED: ${srcMatter} is missing.`);
  console.error('local/ is gitignored — a fresh clone does not have it.');
  process.exit(1);
}
const matterText = parseMatter(fs.readFileSync(srcMatter, 'utf8'));
const pages = {};
for (const [key, page] of Object.entries(MATTER_PAGES)) {
  const sections = page.parts.map(([k]) => k);
  const labels = {};
  const text = {};
  for (const [k, label, chinese] of page.parts) {
    labels[k] = label;
    text[k] = matterText[chinese];
  }
  pages[key] = { slug: page.slug, title: page.title, sections, labels, text };
  console.log(`${page.slug}: ${sections.map((k) => `${k} ${text[k].length}`).join(', ')}`);
}
const matterOut = `// GENERATED by scripts/build-text.js from local/mumonkan-front-and-back-matter.md — do not edit by hand.
export default ${JSON.stringify(pages, null, 2)};
`;
fs.writeFileSync(outMatter, matterOut);
console.log(`Wrote ${outMatter} (${Object.keys(pages).length} pages).`);
