// Rerunnable: local/gateless-gate.txt -> src/koans/text/mumonkan.js
// Run: node scripts/build-text.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseMumonkan } from './lib/parse-mumonkan.js';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcTxt = path.join(root, 'local', 'gateless-gate.txt');
const outFile = path.join(root, 'src', 'koans', 'text', 'mumonkan.js');

// Hand-fixes for any case the uniform rules misparse (id -> partial entry). Empty for now.
const OVERRIDES = {};

const raw = fs.readFileSync(srcTxt, 'utf8');
const { about, cases } = parseMumonkan(raw);
for (const [id, patch] of Object.entries(OVERRIDES)) cases[id] = { ...cases[id], ...patch };

const ids = Object.keys(cases).map(Number).sort((a, b) => a - b);
const problems = [];
for (const id of ids) {
  for (const f of ['title', 'case', 'comment', 'verse']) {
    if (!cases[id][f] || !cases[id][f].trim()) problems.push(`case ${id}: empty ${f}`);
  }
}

console.log('id  verse-len  case-len  comment-len  title');
for (const id of ids) {
  const c = cases[id];
  console.log(
    String(id).padStart(2), String(c.verse.length).padStart(9), String(c.case.length).padStart(8),
    String(c.comment.length).padStart(11), ' ', c.title,
  );
}

if (ids.length !== 49) problems.push(`expected 49 entries, got ${ids.length}`);
if (problems.length) {
  console.error('\nBUILD FAILED:\n' + problems.join('\n'));
  process.exit(1);
}

const body = ids.map((id) => `  ${id}: ${JSON.stringify(cases[id])},`).join('\n');
const out = `// GENERATED by scripts/build-text.js from local/gateless-gate.txt — do not edit by hand.
export const about = ${JSON.stringify(about)};
export default {
${body}
};
`;
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, out);
console.log(`\nWrote ${outFile} (${ids.length} cases).`);
